### ISSUE TITLE
[Feature Request] Ability to Favorite songs in Notification pop-up 

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#147]
### Description

Most apps have the ability to quick add songs from the notification bar, ie Heart icon.

### Solution

Expand the app notification bar to allow to favorite songs

### Alternatives

Can't think of any

### Additional Context

None

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I am currently not considering any notification related changes due to how android displays media notification in different versions of android. Adding any controls manually would affect the interface of the notification depending on the android version. (For example, the shuffle and favorite icon in Spotify's notification in MIUI 13 is very much larger than the over icons)

Closing this since it is unplanned.
