### ISSUE TITLE
detect /f(ea)?t\./i and similar in the song artist field, instead of creating a new artist for every new value in the artist metadata field

### ISSUE THREAD

**Issue by Errorcrafter** [zyrouge/symphony#19]
currently, if a song in my library has the `artist` metadata tag in the format of "X (ft. Y)", the app creates a new artist in the Artists tab named "X (ft. Y)" for that single song, instead of including the song in the tabs for both X and Y. this causes the Artists tab to be bloated with these additional, fake artists, and causes certain songs to be omitted from the Artist page it would normally be in. 

![Screenshot_20221223-131548_Symphony.jpg](https://user-images.githubusercontent.com/69189354/209276132-aa34a822-e9cf-457e-8457-4ec3718b531b.jpg)

this could be probably solved by implementing a regex pattern match for all `artist` metadata tags to look for instances of "ft." or similar and parsing the artist names accordingly

i would create a fork that fixes this but unfortunately i do not know anything about android app development so i am making this issue to bring this problem to your attention.

**Comment by zyrouge** [comment]
Do they have `albumartist` attribute? If so, you can use albums artists tab to browse them. This is something related to metedata and they are handled directly by the `MediaStore`. I'll probably suggest using `albumartist` instead of implementing a hacky solution to do this. Or you can change the `artist` attribute itself.

**Comment by zyrouge** [comment]
Closing this as it is stale.
