### ISSUE TITLE
[Feature Request] Save current queue as playlist

### ISSUE THREAD

**Issue by sophieisqueer** [zyrouge/symphony#244]
### Description

It'd be great to be able to save the current queue to a playlist.

### Solution

An option in the now playing or queue view to allow the user to add the tracks in the queue to a new or existing playlist.

### Alternatives

I believe this is already possible if you start from a playlist and add from there, but sometimes you're just picking songs and want to save it for later, listen to something else in the meantime, etc.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Thank you for your positive feedback! The only reason I haven't added gestures is because Compose doesn't yet have a good way of doing it. So, unless I implement some "hack", this would not be possible. I haven't worked on features like Last.fm integration, statistics, etc. since the app doesn't yet have some core features.
