### ISSUE TITLE
[Feature Request] Buttons to rewind and fast-forward

### ISSUE THREAD

**Issue by sojusnik** [zyrouge/symphony#34]
Buttons to rewind and fast-forward in the "now playing" view, where play and previous/next buttons are located, would make scrolling within a song much easier. Ideally, the time period for rewinding and fast-forwarding should be adjustable in the settings.

The most common position for such buttons would be as follows: (previous) (rewind) (play) (fast-forward) (next)

Would also be helpful, if those two buttons could be added to the notification area of Android.

**Comment by sojusnik** [comment]
If you prefer not adding the play button to the centre, why not move it from the left side to the right side, because you can reach it easier with your right thumb there, assuming that the majority of the people are using their smartphone with their right hand?

**Comment by zyrouge** [comment]
> If you prefer not adding the play button to the centre, why not move it from the left side to the right side, because you can reach it easier with your right thumb there, assuming that the majority of the people are using their smartphone with their right hand?

That's a design choice I would say. This is definitely personal preference, but I am pretty sure most use both the hands while using their phones. Unless there's a demand, I am not going to make design changes on things users have liked. Closing this since it is implemented. You could open a feature request to toggle normal music layout.
